apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeslave1-local-pv-bb
  annotations:
   "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
           { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["kubeslave1.vmntech.com", "kubeslave1"]
            }
          ]}
         ]}
        }'
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /app/db/postgres/data001/bb
